// Every UN member state plus Palestine, Kosovo and Taiwan, as nationalities
// (demonyms), in English and Arabic. A worker's nationality is stored as the
// ISO 3166-1 code (e.g. "EG"), never as typed text, so "Egypt" / "Egyptian" /
// "مصري" can't end up as three different values - and the name shown follows
// the viewer's language. "XX" is the catch-all for anything not listed.
const RAW: [code: string, en: string, ar: string][] = [
  ["AF", "Afghan", "أفغاني"],
  ["AL", "Albanian", "ألباني"],
  ["DZ", "Algerian", "جزائري"],
  ["AD", "Andorran", "أندوري"],
  ["AO", "Angolan", "أنغولي"],
  ["AG", "Antiguan and Barbudan", "من أنتيغوا وباربودا"],
  ["AR", "Argentine", "أرجنتيني"],
  ["AM", "Armenian", "أرميني"],
  ["AU", "Australian", "أسترالي"],
  ["AT", "Austrian", "نمساوي"],
  ["AZ", "Azerbaijani", "أذربيجاني"],
  ["BS", "Bahamian", "باهامي"],
  ["BH", "Bahraini", "بحريني"],
  ["BD", "Bangladeshi", "بنغلاديشي"],
  ["BB", "Barbadian", "بربادوسي"],
  ["BY", "Belarusian", "بيلاروسي"],
  ["BE", "Belgian", "بلجيكي"],
  ["BZ", "Belizean", "بيليزي"],
  ["BJ", "Beninese", "بنيني"],
  ["BT", "Bhutanese", "بوتاني"],
  ["BO", "Bolivian", "بوليفي"],
  ["BA", "Bosnian", "بوسني"],
  ["BW", "Botswanan", "بوتسواني"],
  ["BR", "Brazilian", "برازيلي"],
  ["GB", "British", "بريطاني"],
  ["BN", "Bruneian", "بروناوي"],
  ["BG", "Bulgarian", "بلغاري"],
  ["BF", "Burkinabe", "بوركينابي"],
  ["BI", "Burundian", "بوروندي"],
  ["KH", "Cambodian", "كمبودي"],
  ["CM", "Cameroonian", "كاميروني"],
  ["CA", "Canadian", "كندي"],
  ["CV", "Cape Verdean", "من الرأس الأخضر"],
  ["CF", "Central African", "من أفريقيا الوسطى"],
  ["TD", "Chadian", "تشادي"],
  ["CL", "Chilean", "تشيلي"],
  ["CN", "Chinese", "صيني"],
  ["CO", "Colombian", "كولومبي"],
  ["KM", "Comorian", "قمري"],
  ["CG", "Congolese (Republic of the Congo)", "كونغولي (جمهورية الكونغو)"],
  ["CD", "Congolese (DR Congo)", "كونغولي (الكونغو الديمقراطية)"],
  ["CR", "Costa Rican", "كوستاريكي"],
  ["HR", "Croatian", "كرواتي"],
  ["CU", "Cuban", "كوبي"],
  ["CY", "Cypriot", "قبرصي"],
  ["CZ", "Czech", "تشيكي"],
  ["DK", "Danish", "دنماركي"],
  ["DJ", "Djiboutian", "جيبوتي"],
  ["DM", "Dominican (Dominica)", "دومينيكي (دومينيكا)"],
  ["DO", "Dominican (Dominican Republic)", "دومينيكاني (الدومينيكان)"],
  ["NL", "Dutch", "هولندي"],
  ["TL", "East Timorese", "تيموري"],
  ["EC", "Ecuadorian", "إكوادوري"],
  ["EG", "Egyptian", "مصري"],
  ["AE", "Emirati", "إماراتي"],
  ["GQ", "Equatorial Guinean", "غيني استوائي"],
  ["ER", "Eritrean", "إريتري"],
  ["EE", "Estonian", "إستوني"],
  ["SZ", "Eswatini", "إسواتيني"],
  ["ET", "Ethiopian", "إثيوبي"],
  ["FJ", "Fijian", "فيجي"],
  ["PH", "Filipino", "فلبيني"],
  ["FI", "Finnish", "فنلندي"],
  ["FR", "French", "فرنسي"],
  ["GA", "Gabonese", "غابوني"],
  ["GM", "Gambian", "غامبي"],
  ["GE", "Georgian", "جورجي"],
  ["DE", "German", "ألماني"],
  ["GH", "Ghanaian", "غاني"],
  ["GR", "Greek", "يوناني"],
  ["GD", "Grenadian", "غرينادي"],
  ["GT", "Guatemalan", "غواتيمالي"],
  ["GN", "Guinean", "غيني"],
  ["GW", "Guinea-Bissauan", "غيني بيساوي"],
  ["GY", "Guyanese", "غياني"],
  ["HT", "Haitian", "هايتي"],
  ["HN", "Honduran", "هندوراسي"],
  ["HU", "Hungarian", "مجري"],
  ["IS", "Icelandic", "آيسلندي"],
  ["IN", "Indian", "هندي"],
  ["ID", "Indonesian", "إندونيسي"],
  ["IR", "Iranian", "إيراني"],
  ["IQ", "Iraqi", "عراقي"],
  ["IE", "Irish", "أيرلندي"],
  ["IL", "Israeli", "إسرائيلي"],
  ["IT", "Italian", "إيطالي"],
  ["CI", "Ivorian", "إيفواري"],
  ["JM", "Jamaican", "جامايكي"],
  ["JP", "Japanese", "ياباني"],
  ["JO", "Jordanian", "أردني"],
  ["KZ", "Kazakh", "كازاخستاني"],
  ["KE", "Kenyan", "كيني"],
  ["KI", "I-Kiribati", "كيريباتي"],
  ["XK", "Kosovar", "كوسوفي"],
  ["KW", "Kuwaiti", "كويتي"],
  ["KG", "Kyrgyz", "قيرغيزستاني"],
  ["LA", "Laotian", "لاوسي"],
  ["LV", "Latvian", "لاتفي"],
  ["LB", "Lebanese", "لبناني"],
  ["LS", "Basotho", "ليسوتي"],
  ["LR", "Liberian", "ليبيري"],
  ["LY", "Libyan", "ليبي"],
  ["LI", "Liechtensteiner", "ليختنشتايني"],
  ["LT", "Lithuanian", "ليتواني"],
  ["LU", "Luxembourgish", "لوكسمبورغي"],
  ["MG", "Malagasy", "مدغشقري"],
  ["MW", "Malawian", "مالاوي"],
  ["MY", "Malaysian", "ماليزي"],
  ["MV", "Maldivian", "مالديفي"],
  ["ML", "Malian", "مالي"],
  ["MT", "Maltese", "مالطي"],
  ["MH", "Marshallese", "مارشالي"],
  ["MR", "Mauritanian", "موريتاني"],
  ["MU", "Mauritian", "موريشيوسي"],
  ["MX", "Mexican", "مكسيكي"],
  ["FM", "Micronesian", "ميكرونيزي"],
  ["MD", "Moldovan", "مولدوفي"],
  ["MC", "Monegasque", "موناكي"],
  ["MN", "Mongolian", "منغولي"],
  ["ME", "Montenegrin", "مونتينيغري"],
  ["MA", "Moroccan", "مغربي"],
  ["MZ", "Mozambican", "موزمبيقي"],
  ["MM", "Myanmar", "ميانماري"],
  ["NA", "Namibian", "ناميبي"],
  ["NR", "Nauruan", "ناوروي"],
  ["NP", "Nepalese", "نيبالي"],
  ["NZ", "New Zealander", "نيوزيلندي"],
  ["NI", "Nicaraguan", "نيكاراغوي"],
  ["NE", "Nigerien", "نيجري"],
  ["NG", "Nigerian", "نيجيري"],
  ["KP", "North Korean", "كوري شمالي"],
  ["MK", "North Macedonian", "مقدوني شمالي"],
  ["NO", "Norwegian", "نرويجي"],
  ["OM", "Omani", "عماني"],
  ["PK", "Pakistani", "باكستاني"],
  ["PW", "Palauan", "بالاوي"],
  ["PS", "Palestinian", "فلسطيني"],
  ["PA", "Panamanian", "بنمي"],
  ["PG", "Papua New Guinean", "من بابوا غينيا الجديدة"],
  ["PY", "Paraguayan", "باراغوياني"],
  ["PE", "Peruvian", "بيروفي"],
  ["PL", "Polish", "بولندي"],
  ["PT", "Portuguese", "برتغالي"],
  ["QA", "Qatari", "قطري"],
  ["RO", "Romanian", "روماني"],
  ["RU", "Russian", "روسي"],
  ["RW", "Rwandan", "رواندي"],
  ["KN", "Kittitian and Nevisian", "من سانت كيتس ونيفيس"],
  ["LC", "Saint Lucian", "من سانت لوسيا"],
  ["VC", "Vincentian", "من سانت فينسنت والغرينادين"],
  ["SV", "Salvadoran", "سلفادوري"],
  ["WS", "Samoan", "ساموي"],
  ["SM", "Sammarinese", "سان مارينو"],
  ["ST", "Sao Tomean", "من ساو تومي وبرينسيبي"],
  ["SA", "Saudi", "سعودي"],
  ["SN", "Senegalese", "سنغالي"],
  ["RS", "Serbian", "صربي"],
  ["SC", "Seychellois", "سيشيلي"],
  ["SL", "Sierra Leonean", "سيراليوني"],
  ["SG", "Singaporean", "سنغافوري"],
  ["SK", "Slovak", "سلوفاكي"],
  ["SI", "Slovenian", "سلوفيني"],
  ["SB", "Solomon Islander", "من جزر سليمان"],
  ["SO", "Somali", "صومالي"],
  ["ZA", "South African", "جنوب أفريقي"],
  ["KR", "South Korean", "كوري جنوبي"],
  ["SS", "South Sudanese", "جنوب سوداني"],
  ["ES", "Spanish", "إسباني"],
  ["LK", "Sri Lankan", "سريلانكي"],
  ["SD", "Sudanese", "سوداني"],
  ["SR", "Surinamese", "سورينامي"],
  ["SE", "Swedish", "سويدي"],
  ["CH", "Swiss", "سويسري"],
  ["SY", "Syrian", "سوري"],
  ["TW", "Taiwanese", "تايواني"],
  ["TJ", "Tajik", "طاجيكي"],
  ["TZ", "Tanzanian", "تنزاني"],
  ["TH", "Thai", "تايلاندي"],
  ["TG", "Togolese", "توغولي"],
  ["TO", "Tongan", "تونغي"],
  ["TT", "Trinidadian and Tobagonian", "من ترينيداد وتوباغو"],
  ["TN", "Tunisian", "تونسي"],
  ["TR", "Turkish", "تركي"],
  ["TM", "Turkmen", "تركمانستاني"],
  ["TV", "Tuvaluan", "توفالي"],
  ["UG", "Ugandan", "أوغندي"],
  ["UA", "Ukrainian", "أوكراني"],
  ["US", "American", "أمريكي"],
  ["UY", "Uruguayan", "أوروغواياني"],
  ["UZ", "Uzbek", "أوزبكستاني"],
  ["VU", "Vanuatuan", "فانواتي"],
  ["VE", "Venezuelan", "فنزويلي"],
  ["VN", "Vietnamese", "فيتنامي"],
  ["YE", "Yemeni", "يمني"],
  ["ZM", "Zambian", "زامبي"],
  ["ZW", "Zimbabwean", "زيمبابوي"],
];

const OTHER = { code: "XX", en: "Other", ar: "أخرى" };

const ALL = [
  ...RAW.map(([code, en, ar]) => ({ code, en, ar })),
  OTHER,
];

const BY_CODE = new Map(ALL.map((n) => [n.code, n]));

// Legacy rows (typed before this list existed) aren't a known code, so fall
// back to showing exactly what was stored rather than hiding it.
export function nationalityLabel(value: string, locale: string): string {
  const entry = BY_CODE.get(value);
  if (!entry) return value;
  return locale === "ar" ? entry.ar : entry.en;
}

// Alphabetical in the viewer's language, with Egyptian pinned first (the main
// market) and "Other" last.
export function nationalityOptions(
  locale: string
): { code: string; label: string }[] {
  const collator = new Intl.Collator(locale === "ar" ? "ar" : "en");
  const label = (n: { en: string; ar: string }) =>
    locale === "ar" ? n.ar : n.en;

  const middle = ALL.filter((n) => n.code !== "EG" && n.code !== "XX").sort(
    (a, b) => collator.compare(label(a), label(b))
  );

  return [BY_CODE.get("EG")!, ...middle, OTHER].map((n) => ({
    code: n.code,
    label: label(n),
  }));
}
